"use client";

import { motion } from "framer-motion";
import { ArrowRight, BarChart3, Check, ChevronRight, FileText, Globe2, Menu, Radio, Send, ShieldCheck, Sparkles, X } from "lucide-react";
import { useState } from "react";
import type React from "react";
import { Card, Logo, StatusBadge } from "./ui";

const fade = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };
const tiers: Array<[string, string, string, string[]]> = [
  ["Hobby", "Untuk proyek personal", "$0", ["5 monitors", "5-minute checks", "Email alerts"]],
  ["Pro", "Untuk tim yang terus bergerak", "$19", ["50 monitors", "1-minute checks", "Global probes", "All alert channels"]],
  ["Enterprise", "Untuk skala tanpa batas", "Custom", ["Unlimited monitors", "SLA reports", "SSO & audit logs"]],
];

function PingPlayground() {
  const [url, setUrl] = useState("api.pingsmith.dev");
  const [checking, setChecking] = useState(false);
  const run = () => { setChecking(true); window.setTimeout(() => setChecking(false), 1050); };
  return <section className="mx-auto max-w-5xl px-5 py-24"><Card className="overflow-hidden border-cyan-400/20 bg-[linear-gradient(135deg,_rgba(15,23,42,0.96),_rgba(17,24,39,0.88),_rgba(15,118,110,0.24))] p-6 shadow-[0_20px_80px_rgba(14,165,233,0.18)] sm:p-9"><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-semibold text-cyan-300">INTERACTIVE PING PLAYGROUND</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-white">Lihat dunia merespons endpoint Anda.</h2><p className="mt-3 text-slate-400">Jalankan simulasi pemeriksaan multi-region dalam sekejap.</p><div className="mt-7 flex rounded-2xl border border-cyan-400/20 bg-[#0B0F17]/80 p-1.5 shadow-inner shadow-cyan-500/10 focus-within:border-cyan-400/60"><Globe2 className="m-2 text-slate-500" size={19}/><input aria-label="Endpoint URL" value={url} onChange={(e) => setUrl(e.target.value)} className="min-w-0 flex-1 bg-transparent px-1 text-sm text-white outline-none placeholder:text-slate-500" placeholder="https://example.com" /><button onClick={run} className="rounded-xl bg-gradient-to-r from-cyan-300 to-sky-400 px-4 py-2 text-sm font-bold text-slate-950 hover:brightness-110">{checking ? "Checking…" : "Ping now"}</button></div></div><div className="space-y-3">{[["Singapore",24],["Virginia",112],["Frankfurt",168]].map(([node, ms], i) => <motion.div animate={checking ? { opacity: [.35,1,.35], y: [0, -2, 0] } : { opacity: 1, y: 0 }} transition={{ repeat: checking ? Infinity : 0, delay: i*.12 }} key={node} className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#0B0F17]/70 p-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]"><span className="flex items-center gap-2 text-sm text-slate-200"><Radio size={16} className="text-cyan-300"/>{node}</span><motion.b key={checking ? "run" : "idle"} initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-cyan-300">{checking ? "…" : ms+" ms"}</motion.b></motion.div>)}</div></div></Card></section>;
}

export function LandingPage() {
  const [annual, setAnnual] = useState(true);
  const [menu, setMenu] = useState(false);
  return <section id="top" className="relative overflow-hidden bg-[#070b12] text-white"><div className="pointer-events-none absolute inset-x-0 top-0 h-[620px] bg-[radial-gradient(circle_at_top,_rgba(34,211,238,0.22),_transparent_50%)]"/><div className="pointer-events-none absolute inset-x-0 top-0 h-[460px] bg-[linear-gradient(120deg,_rgba(34,211,238,0.08),_transparent_42%,_rgba(59,130,246,0.08))]"/><nav className="relative mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><div className="rounded-full border border-white/10 bg-white/5 px-3 py-2 backdrop-blur-xl"><Logo/></div><div className="hidden items-center gap-8 text-sm text-slate-300 md:flex"><a href="#features" className="transition hover:text-cyan-300">Features</a><a href="#pricing" className="transition hover:text-cyan-300">Pricing</a><a href="#dashboard" className="transition hover:text-cyan-300">Docs</a></div><div className="hidden items-center gap-3 sm:flex"><button className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-200 transition hover:border-cyan-400/40 hover:text-cyan-200">Sign In</button><button className="rounded-full bg-gradient-to-r from-cyan-300 via-sky-400 to-blue-500 px-4 py-2.5 text-sm font-bold text-slate-950 shadow-[0_0_35px_rgba(34,211,238,0.45)] transition hover:scale-[1.02]">Get Started Free</button></div><button onClick={() => setMenu(!menu)} className="rounded-full border border-white/10 bg-white/5 p-2 sm:hidden" aria-label="Toggle navigation">{menu ? <X/> : <Menu/>}</button>{menu && <div className="absolute right-5 top-16 z-10 grid w-44 gap-3 rounded-2xl border border-white/10 bg-[#0f172a]/90 p-4 text-sm shadow-2xl backdrop-blur-xl"><a href="#features" className="text-slate-200">Features</a><a href="#pricing" className="text-slate-200">Pricing</a><button className="rounded-lg bg-cyan-300 p-2 font-bold text-slate-950">Get Started</button></div>}</nav>
    <motion.div initial="hidden" animate="visible" transition={{ staggerChildren: .12 }} className="relative mx-auto max-w-6xl px-5 pb-4 pt-16 text-center sm:pt-24"><motion.div variants={fade} className="mx-auto inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-xs font-medium text-cyan-200 shadow-[0_0_24px_rgba(34,211,238,0.18)]"><Sparkles size={13}/>v2.0 Real-time Ping Engine Released <ChevronRight size={13}/></motion.div><motion.h1 variants={fade} className="mx-auto mt-6 max-w-5xl text-4xl font-black tracking-[-.055em] text-white sm:text-6xl lg:text-7xl">Pantau Ketersediaan Server <span className="bg-gradient-to-r from-cyan-300 via-sky-300 to-blue-400 bg-clip-text text-transparent">Tanpa Blindspot</span></motion.h1><motion.p variants={fade} className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">Pantau API, website, port, DNS, dan SSL dari node global. Deteksi insiden lebih cepat sebelum pengguna Anda menyadarinya.</motion.p><motion.div variants={fade} className="mt-8 flex justify-center gap-3"><button className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-cyan-300 via-sky-400 to-blue-500 px-5 py-3 font-bold text-slate-950 shadow-[0_15px_40px_rgba(34,211,238,0.35)] transition hover:scale-[1.02]">Start monitoring free <ArrowRight size={17}/></button><a href="#features" className="rounded-full border border-white/10 bg-white/5 px-5 py-3 font-semibold text-slate-200 transition hover:border-cyan-300/40 hover:text-cyan-200">Explore features</a></motion.div><DashboardMockup/></motion.div>
    <PingPlayground/>
    <section id="features" className="mx-auto max-w-6xl px-5 py-16"><div className="mb-10 max-w-xl"><p className="text-sm font-bold text-cyan-300">BUILT FOR RELIABILITY</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-white sm:text-4xl">Semua sinyal. Satu command center.</h2></div><div className="grid gap-4 md:grid-cols-4"><Feature icon={<Globe2/>} title="Global probes map" text="Perspektif pengguna dari setiap region yang penting." wide/><Feature icon={<Send/>} title="Multi-channel alerts" text="Telegram, Discord, Email & webhooks."/><Feature icon={<BarChart3/>} title="Latency analytics" text="Temukan tren sebelum menjadi insiden."/><Feature icon={<FileText/>} title="SLA reports" text="Laporan ketersediaan siap dibagikan." wide/><Feature icon={<ShieldCheck/>} title="Intelligent incident engine" text="Kurangi alert noise dengan verifikasi lintas lokasi." wide/></div></section>
    <section id="pricing" className="mx-auto max-w-6xl px-5 py-24"><div className="text-center"><p className="text-sm font-bold text-cyan-300">SIMPLE, SCALABLE PRICING</p><h2 className="mt-3 text-3xl font-bold text-white sm:text-4xl">Mulai kecil. Pantau tanpa batas.</h2><div className="mt-6 inline-flex rounded-full border border-white/10 bg-white/5 p-1 backdrop-blur"><button onClick={() => setAnnual(false)} className={!annual ? "rounded-full bg-[#263044] px-4 py-1.5 text-sm text-white" : "rounded-full px-4 py-1.5 text-sm text-slate-400"}>Monthly</button><button onClick={() => setAnnual(true)} className={annual ? "rounded-full bg-[#263044] px-4 py-1.5 text-sm text-white" : "rounded-full px-4 py-1.5 text-sm text-slate-400"}>Yearly <span className="text-cyan-300">-20%</span></button></div></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{tiers.map(([name, desc, price, features]) => <div key={name} className={name === "Pro" ? "rounded-2xl bg-gradient-to-br from-cyan-400/40 via-sky-500/10 to-transparent p-[1px] shadow-[0_0_35px_rgba(34,211,238,0.18)]" : ""}><Card className={name === "Pro" ? "h-full rounded-[15px] border-cyan-400/20 bg-[#101827] p-6" : "h-full p-6"}><p className="font-bold text-white">{name}</p><p className="mt-2 h-10 text-sm text-slate-400">{desc}</p><p className="my-6 text-4xl font-black text-white">{name === "Pro" && !annual ? "$24" : price}<span className="text-sm font-normal text-slate-500">{String(price).startsWith("$") ? "/mo" : ""}</span></p><button className={name === "Pro" ? "w-full rounded-full bg-gradient-to-r from-cyan-300 via-sky-400 to-blue-500 py-2.5 text-sm font-bold text-slate-950" : "w-full rounded-full border border-[#30394b] py-2.5 text-sm font-bold text-white"}>{name === "Enterprise" ? "Talk to sales" : "Start free"}</button><ul className="mt-6 space-y-3">{(features as string[]).map((f) => <li key={f} className="flex gap-2 text-sm text-slate-300"><Check size={16} className="shrink-0 text-emerald-400"/>{f}</li>)}</ul></Card></div>)}</div></section>
    <footer className="border-t border-white/10 bg-[#050a12]"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-5 py-9 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><Logo/><span>© 2026 Pingsmith Monitor</span><span className="flex items-center gap-2 text-emerald-400"><i className="size-2 rounded-full bg-emerald-400 animate-ping-dot"/>All Systems Operational</span></div></footer>
  </section>;
}

function DashboardMockup() {
  return <motion.div whileHover={{ rotateX: 3, rotateY: -3, scale: 1.01 }} transition={{ type: "spring", stiffness: 180, damping: 18 }} className="mx-auto mt-16 max-w-5xl rounded-[28px] border border-cyan-300/20 bg-[#111722]/90 p-3 shadow-[0_30px_100px_rgba(0,242,254,.13)]"><div className="overflow-hidden rounded-[22px] border border-[#222938] bg-[#0B0F17]"><div className="flex items-center gap-2 border-b border-[#222938] bg-white/[0.03] px-4 py-3"><span className="size-2.5 rounded-full bg-rose-400"/><span className="size-2.5 rounded-full bg-amber-400"/><span className="size-2.5 rounded-full bg-emerald-400"/><span className="ml-3 text-xs uppercase tracking-[0.22em] text-slate-500">dashboard.pingsmith.dev</span></div><div className="grid gap-4 p-5 md:grid-cols-[1fr_1.7fr]"><div className="space-y-3">{["production-api","customer-web","postgres-primary"].map((m, i) => <div key={m} className="flex items-center justify-between rounded-2xl border border-[#222938] bg-[linear-gradient(135deg,_rgba(17,24,39,0.95),_rgba(22,31,45,0.92))] p-3 text-sm shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]"><span className="text-slate-200"><span className="mr-2 inline-block size-2 rounded-full bg-emerald-400 animate-ping-dot"/>{m}</span><span className="text-slate-400">{42+i*16}ms</span></div>)}</div><div className="rounded-2xl border border-[#222938] bg-[linear-gradient(135deg,_rgba(17,24,39,0.96),_rgba(15,118,110,0.16))] p-5"><div className="mb-7 flex items-center justify-between"><div><p className="text-sm font-medium text-slate-200">Global response time</p><p className="text-xs text-slate-500">Last 24 hours</p></div><StatusBadge status="UP"/></div><svg className="h-28 w-full" viewBox="0 0 440 110" aria-label="Response time chart"><path d="M0 79 C25 60 36 86 59 71 S100 48 128 62 S164 40 195 58 S240 74 266 38 S301 52 325 35 S374 63 402 34 S425 45 440 22" fill="none" stroke="#00F2FE" strokeWidth="3"/></svg></div></div></div></motion.div>;
}

function Feature({ icon, title, text, wide = false }: { icon: React.ReactNode; title: string; text: string; wide?: boolean }) {
  return <Card className={"group min-h-56 border-white/10 bg-[linear-gradient(180deg,_rgba(15,23,42,0.9),_rgba(17,24,39,0.95))] p-6 transition duration-300 hover:-translate-y-1 hover:border-cyan-400/30 hover:shadow-[0_15px_35px_rgba(34,211,238,0.12)] "+(wide ? "md:col-span-2" : "")}><span className="inline-flex rounded-2xl border border-cyan-400/20 bg-cyan-300/10 p-3 text-cyan-300 shadow-[0_0_25px_rgba(34,211,238,0.12)]">{icon}</span><h3 className="mt-10 text-lg font-bold text-white">{title}</h3><p className="mt-2 text-sm text-slate-400">{text}</p></Card>;
}
